version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pedidos_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pedidos_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata_pedidos:/var/lib/postgresql/data

volumes:
  pgdata_pedidos: