services:
  - type: web
    name: desafio-pedidos-api
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: DB_URL
        sync: false
      - key: RABBITMQ_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false

  - type: web
    name: desafio-pedidos-payments
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile.payments
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: DB_URL
        sync: false
      - key: RABBITMQ_URL
        sync: false

  - type: web
    name: desafio-pedidos-rag
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile.rag
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: RAG_CORS_ALLOWED_ORIGINS
        sync: false
