// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clientes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCliente = `-- name: CreateCliente :one
INSERT INTO clientes (name, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, name, email, password_hash, created_at
`

type CreateClienteParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateCliente(ctx context.Context, arg CreateClienteParams) (Cliente, error) {
	row := q.db.QueryRow(ctx, createCliente, arg.Name, arg.Email, arg.PasswordHash)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getCliente = `-- name: GetCliente :one
SELECT id, name, email, password_hash, created_at
FROM clientes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCliente(ctx context.Context, id pgtype.UUID) (Cliente, error) {
	row := q.db.QueryRow(ctx, getCliente, id)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listClientes = `-- name: ListClientes :many
SELECT id, name, email, password_hash, created_at
FROM clientes
ORDER BY created_at DESC
`

func (q *Queries) ListClientes(ctx context.Context) ([]Cliente, error) {
	rows, err := q.db.Query(ctx, listClientes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cliente
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
