// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Cliente struct {
	ID           uuid.UUID        `json:"id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type ItensPedido struct {
	ID            uuid.UUID `json:"id"`
	PedidoID      uuid.UUID `json:"pedido_id"`
	ProdutoID     string    `json:"produto_id"`
	Quantidade    int32     `json:"quantidade"`
	PrecoUnitario float64   `json:"preco_unitario"`
}

type Pedido struct {
	ID        uuid.UUID        `json:"id"`
	ClienteID uuid.UUID        `json:"cliente_id"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Produto struct {
	ID      string  `json:"id"`
	Nome    string  `json:"nome"`
	Preco   float64 `json:"preco"`
	Estoque int32   `json:"estoque"`
}
