// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProcessedEvent = `-- name: CreateProcessedEvent :exec
INSERT INTO processed_events (order_id, saga_id, status)
VALUES ($1, $2, $3)
`

type CreateProcessedEventParams struct {
	OrderID uuid.UUID `json:"order_id"`
	SagaID  uuid.UUID `json:"saga_id"`
	Status  string    `json:"status"`
}

func (q *Queries) CreateProcessedEvent(ctx context.Context, arg CreateProcessedEventParams) error {
	_, err := q.db.Exec(ctx, createProcessedEvent, arg.OrderID, arg.SagaID, arg.Status)
	return err
}

const getProcessedEvent = `-- name: GetProcessedEvent :one
SELECT order_id, saga_id, status, processed_at
FROM processed_events
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetProcessedEvent(ctx context.Context, orderID uuid.UUID) (ProcessedEvent, error) {
	row := q.db.QueryRow(ctx, getProcessedEvent, orderID)
	var i ProcessedEvent
	err := row.Scan(
		&i.OrderID,
		&i.SagaID,
		&i.Status,
		&i.ProcessedAt,
	)
	return i, err
}
