// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pedidos.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createItemPedido = `-- name: CreateItemPedido :one
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario)
VALUES ($1, $2, $3, $4)
RETURNING id, pedido_id, produto_id, quantidade, preco_unitario
`

type CreateItemPedidoParams struct {
	PedidoID      uuid.UUID `json:"pedido_id"`
	ProdutoID     string    `json:"produto_id"`
	Quantidade    int32     `json:"quantidade"`
	PrecoUnitario float64   `json:"preco_unitario"`
}

// Adiciona um produto dentro do carrinho do pedido
func (q *Queries) CreateItemPedido(ctx context.Context, arg CreateItemPedidoParams) (ItensPedido, error) {
	row := q.db.QueryRow(ctx, createItemPedido,
		arg.PedidoID,
		arg.ProdutoID,
		arg.Quantidade,
		arg.PrecoUnitario,
	)
	var i ItensPedido
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.ProdutoID,
		&i.Quantidade,
		&i.PrecoUnitario,
	)
	return i, err
}

const createPedido = `-- name: CreatePedido :one
INSERT INTO pedidos (cliente_id)
VALUES ($1)
RETURNING id, cliente_id, status, created_at
`

// Cria a "capa" do pedido vinculada a um cliente. O status padrão ('PENDING') e o ID são gerados pelo banco.
func (q *Queries) CreatePedido(ctx context.Context, clienteID uuid.UUID) (Pedido, error) {
	row := q.db.QueryRow(ctx, createPedido, clienteID)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getItensPedido = `-- name: GetItensPedido :many
SELECT id, pedido_id, produto_id, quantidade, preco_unitario
FROM itens_pedido
WHERE pedido_id = $1
`

// Busca todos os itens cadastrados de um pedido específico
func (q *Queries) GetItensPedido(ctx context.Context, pedidoID uuid.UUID) ([]ItensPedido, error) {
	rows, err := q.db.Query(ctx, getItensPedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItensPedido
	for rows.Next() {
		var i ItensPedido
		if err := rows.Scan(
			&i.ID,
			&i.PedidoID,
			&i.ProdutoID,
			&i.Quantidade,
			&i.PrecoUnitario,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPedidoByID = `-- name: GetPedidoByID :one
SELECT id, cliente_id, status, created_at
FROM pedidos
WHERE id = $1 LIMIT 1
`

// Busca os detalhes da capa do pedido para validações
func (q *Queries) GetPedidoByID(ctx context.Context, id uuid.UUID) (Pedido, error) {
	row := q.db.QueryRow(ctx, getPedidoByID, id)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPedidosPaginado = `-- name: ListPedidosPaginado :many
SELECT id, cliente_id, status, created_at
FROM pedidos
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPedidosPaginadoParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Busca pedidos do banco com limite e deslocamento (paginação)
func (q *Queries) ListPedidosPaginado(ctx context.Context, arg ListPedidosPaginadoParams) ([]Pedido, error) {
	rows, err := q.db.Query(ctx, listPedidosPaginado, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pedido
	for rows.Next() {
		var i Pedido
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePedidoStatus = `-- name: UpdatePedidoStatus :exec
UPDATE pedidos
SET status = $2
WHERE id = $1
`

type UpdatePedidoStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// Usado pelas rotas de Pagar e Cancelar para mudar o status ('PAID' ou 'CANCELED')
func (q *Queries) UpdatePedidoStatus(ctx context.Context, arg UpdatePedidoStatusParams) error {
	_, err := q.db.Exec(ctx, updatePedidoStatus, arg.ID, arg.Status)
	return err
}
