// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pedidos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItemPedido = `-- name: CreateItemPedido :one
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario)
VALUES ($1, $2, $3, $4)
RETURNING id, pedido_id, produto_id, quantidade, preco_unitario
`

type CreateItemPedidoParams struct {
	PedidoID      pgtype.UUID    `json:"pedido_id"`
	ProdutoID     string         `json:"produto_id"`
	Quantidade    int32          `json:"quantidade"`
	PrecoUnitario pgtype.Numeric `json:"preco_unitario"`
}

// Adiciona um produto dentro do carrinho do pedido
func (q *Queries) CreateItemPedido(ctx context.Context, arg CreateItemPedidoParams) (ItensPedido, error) {
	row := q.db.QueryRow(ctx, createItemPedido,
		arg.PedidoID,
		arg.ProdutoID,
		arg.Quantidade,
		arg.PrecoUnitario,
	)
	var i ItensPedido
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.ProdutoID,
		&i.Quantidade,
		&i.PrecoUnitario,
	)
	return i, err
}

const createPedido = `-- name: CreatePedido :one
INSERT INTO pedidos (cliente_id)
VALUES ($1)
RETURNING id, cliente_id, status, created_at
`

// Cria a "capa" do pedido vinculada a um cliente. O status padrão ('PENDING') e o ID são gerados pelo banco.
func (q *Queries) CreatePedido(ctx context.Context, clienteID pgtype.UUID) (Pedido, error) {
	row := q.db.QueryRow(ctx, createPedido, clienteID)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPedidoByID = `-- name: GetPedidoByID :one
SELECT id, cliente_id, status, created_at
FROM pedidos
WHERE id = $1 LIMIT 1
`

// Busca os detalhes da capa do pedido para validações
func (q *Queries) GetPedidoByID(ctx context.Context, id pgtype.UUID) (Pedido, error) {
	row := q.db.QueryRow(ctx, getPedidoByID, id)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updatePedidoStatus = `-- name: UpdatePedidoStatus :exec
UPDATE pedidos
SET status = $2
WHERE id = $1
`

type UpdatePedidoStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Usado pelas rotas de Pagar e Cancelar para mudar o status ('PAID' ou 'CANCELED')
func (q *Queries) UpdatePedidoStatus(ctx context.Context, arg UpdatePedidoStatusParams) error {
	_, err := q.db.Exec(ctx, updatePedidoStatus, arg.ID, arg.Status)
	return err
}
