// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: produtos.sql

package db

import (
	"context"
)

const createProduto = `-- name: CreateProduto :one
INSERT INTO produtos (id, nome, preco, estoque)
VALUES ($1, $2, $3, $4)
RETURNING id, nome, preco, estoque
`

type CreateProdutoParams struct {
	ID      string  `json:"id"`
	Nome    string  `json:"nome"`
	Preco   float64 `json:"preco"`
	Estoque int32   `json:"estoque"`
}

func (q *Queries) CreateProduto(ctx context.Context, arg CreateProdutoParams) (Produto, error) {
	row := q.db.QueryRow(ctx, createProduto,
		arg.ID,
		arg.Nome,
		arg.Preco,
		arg.Estoque,
	)
	var i Produto
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Preco,
		&i.Estoque,
	)
	return i, err
}

const devolverEstoque = `-- name: DevolverEstoque :exec
UPDATE produtos
SET estoque = estoque + $2
WHERE id = $1
`

type DevolverEstoqueParams struct {
	ID      string `json:"id"`
	Estoque int32  `json:"estoque"`
}

func (q *Queries) DevolverEstoque(ctx context.Context, arg DevolverEstoqueParams) error {
	_, err := q.db.Exec(ctx, devolverEstoque, arg.ID, arg.Estoque)
	return err
}

const getProduto = `-- name: GetProduto :one
SELECT id, nome, preco, estoque
FROM produtos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduto(ctx context.Context, id string) (Produto, error) {
	row := q.db.QueryRow(ctx, getProduto, id)
	var i Produto
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Preco,
		&i.Estoque,
	)
	return i, err
}

const listProdutos = `-- name: ListProdutos :many
SELECT id, nome, preco, estoque
FROM produtos
ORDER BY nome ASC
`

func (q *Queries) ListProdutos(ctx context.Context) ([]Produto, error) {
	rows, err := q.db.Query(ctx, listProdutos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Produto
	for rows.Next() {
		var i Produto
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Preco,
			&i.Estoque,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reduzirEstoque = `-- name: ReduzirEstoque :exec
UPDATE produtos
SET estoque = estoque - $2
WHERE id = $1
`

type ReduzirEstoqueParams struct {
	ID      string `json:"id"`
	Estoque int32  `json:"estoque"`
}

func (q *Queries) ReduzirEstoque(ctx context.Context, arg ReduzirEstoqueParams) error {
	_, err := q.db.Exec(ctx, reduzirEstoque, arg.ID, arg.Estoque)
	return err
}
